In [ ]:
#Importieren der NumPy Bibliothek 
import numpy as np

Beispiel 1: Arrays erstellen

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


Beispiel 2: 2 Arrays addieren

In [ ]:
c = a+b
print(c)

[ 7  9 11 13 15]


Beispiel 3: 2 Arrays konkatenieren

In [ ]:
d = np.concatenate((a, b))
print(d)

[ 1  2  3  4  5  6  7  8  9 10]


Beispiel 4: Bestimmung statistischer Kennzahlen eines Datensatzes

In [ ]:
#Bestimmen von Minimum und Maximum

arr = np.array([[1,23,78],[98,60,75],[79,25,48]])  
print(arr)
#Minimum Funktion
print(np.amin(arr))
#Maximum Funktion
print(np.amax(arr))

[[ 1 23 78]
 [98 60 75]
 [79 25 48]]
1
98


In [ ]:
#Bestimmen des Durchschnitts

a = np.array([5,6,7]) 
print(a)
print(np.mean(a))

[5 6 7]
6.0


In [ ]:
#Bestimmen der Standardabweichung

a = np.array([5,6,7]) 
print(a)
print(np.std(a))

[5 6 7]
0.816496580927726


Beispiel 5: Reshaping von Array-Dimensionen

In [ ]:
#Reshaping eines Array

#Erstellen eines 1-Dimensionalen Array
oneDimensionalData = np.array([1, 2, 3, 4, 5, 6])

print(oneDimensionalData)

#Reshape in 2-Dimensionales Array
twoDimensionalArray = oneDimensionalData.reshape(len(oneDimensionalData), 1)

print(twoDimensionalArray)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
